### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by boronine** [leira/base16-kakoune#2]
Can you add a license? The README here recommends MIT: https://github.com/chriskempson/base16-templates-source

**Comment by TeddyDD** [comment]
Yeah, license is must-have, for now this is basically All rights reserved repo

**Comment by TeddyDD** [comment]
Hey @leira If you are not interested in mainlining this repo, could you please consider adding license so I can fork it legally?

Otherwise I'll be forced to write template from scratch because by **default your work is All Rights Reserved**.

**Comment by leira** [comment]
@TeddyDD Sorry for the delay, license added.
